spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: micoservicecloud-config-dev
---
spring:
    profiles: test
    application:
        name: micoservicecloud-config-test